[main]
url = "https://github.com/Chudy34/delegacje/archive/refs/heads/main.tar.gz"
format = "tar.gz"
extract = true
autoupdate.strategy = "latest_github_tag"
autoupdate.upstream = "https://github.com/Chudy34/delegacje"
